acme/urls.py
from django.conf import settings #toolbar
from django.conf.urls import url #toolbar


from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('blog/', include('blog.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/urls.py
# from django.urls import include, path
from django.conf.urls import url

from . import views


app_name = 'blog'

urlpatterns = [
    # path('', views.home),
    # path('about/', views.about),
    url(r'^$', views.index, name='index'),
    url(r'^posts/(?P<id>[0-9]+)$', views.show, name='show'),
]

blog/models.py
from django.db import models

class TimespamtedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True #Timespamted hérite de Model et est une classe abstraite qu'on ne peut pas instancier

# Create your models here.
class Post(TimespamtedModel): # du coup ça hérite de Model et de TimespantedModel
    title = models.CharField(max_length=255)
    body = models.TextField()


    def __str__(self):
        return self.title # plus jolie quand on fait from blog.models import Post puis Post.objects.all()

acme/views.py
# from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    # return HttpResponse('hello')
    return render(request, 'pages/home.html')

def about(request):
    return render(request, 'pages/about.html')

def contact(request):
    return render(request, 'pages/contact.html')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404

# from .mocks import Post
from .models import Post

# Create your views here.
def index(request):
    # posts = []
    # posts = Post.all()
    posts = Post.objects.all()
    return render(request, 'blog/index.html', {'posts': posts})

def show(request, id):
    # post = Post.find(id)
    post = get_object_or_404(Post, pk=id)
    # try:
    #     post = Post.objects.get(pk=id)
    # except Post.DoesNotExist:
    #     # return {'id': 0, 'title': 'Sorry no post', 'body': ''}
    #     raise Http404('Sorry') # fonctionne avec raise :-)

    return render(request, 'blog/show.html', {'post' : post})

blog/templates/blog/index.html
{% extends 'layouts/base.html' %}
{% block title %}Acme all posts{% endblock %}
{% block content %}
    <h1>blog ({{ posts|length }} posts)</h1>
    {% for post in posts %}
            <article>
                <h2>#{{ post.id }} - {{ post.title|upper }}</h2>
                <p>{{ post.body|truncatewords:3 }}</p>
                <p><a href="/blog/posts/{{ post.id }}">Lire la suite</a></p>
                <p>ou le même lien mais pas en hard donc mieux :</p>
                <p><a href="{% url 'blog:show' id=post.id %}">Lire la suite</a></p>
            </article>
        {% if not forloop.last %}
            <hr>
        {% endif %}
    {% empty %}
            <p>No post avalable</p>
    {% endfor %}

{% endblock %}

blog/templates/blog/show.html
{% extends 'layouts/base.html' %}
{% block title %}Acme {{ post.title }}{% endblock %}
{% block content %}
    <article>
        <h1>#{{ post.id }} - {{ post.title }}</h1>
        <p>{{ post.body }}</p>
        <a href="{% url 'blog:index' %}">go to blog index</a>
    </article>
{% endblock %}

templates/layouts/_footer.html
<footer>
    <p>&copy; Copyright {% now 'Y' %} Acme &middot; All rights reserved!</p>
</footer>

templates/layouts/_nav.html
<nav>
    <a href="#">ACME</a>
    <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'blog:index' %}">Blog</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'contact' %}">Contact</a></li>
    </ul>
</nav>

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Acme{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'layouts/_nav.html' %}
    {% block content %}Toto{% endblock %}
    {% include 'layouts/_footer.html' %}
</body>
</html>

templates/pages/about.html
{% extends 'layouts/base.html' %}
{% block title %}Acme all posts{% endblock %}
{% block content %}
<h1>about</h1>
{% endblock %}

templates/pages/contact.html
{% extends 'layouts/base.html' %}
{% block title %}Acme all posts{% endblock %}
{% block content %}
<h1>contact</h1>
{% endblock %}

templates/pages/home.html
{% extends 'layouts/base.html' %}
{% block title %}Acme home{% endblock %}

{% block content %}
    <h1>hello Cyriloup</h1>


    <p>Je suis un serveur Django de test</p>

    <p>Je suis happy :)</p>

    <a href="{% url 'blog:index' %}">go to blog index</a>
{% endblock %}